//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub email_verified: bool,
    pub first_name: String,
    pub last_name: String,
    pub password_hash: Option<String>,
    pub password_salt: Option<String>,
    pub password_algo: Option<String>,
    pub password_params: Option<String>,
    pub failed_login_count: i32,
    pub locked_until: Option<DateTimeWithTimeZone>,
    pub two_factor_enabled: bool,
    pub must_change_password: bool,
    pub permission_level: String,
    pub last_login_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::password_reset_token::Entity")]
    PasswordResetToken,
}

impl Related<super::password_reset_token::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PasswordResetToken.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
